services:
  - type: web
    name: fastapi-m4a-downloader
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 7860
    autoDeploy: true
